version: '3.8'

services:
  web:
    build: ./web-app
    command: python app.py runserver
    volumes:
      - ./web-app/:/usr/src/app/
    ports:
      - 5000:5000
    depends_on:
    - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=iuquizdb

volumes:
  postgres_data: