"""Update usage of quiz_games status property

Revision ID: dcb1a0d764ee
Revises: 9a22d1c0c7a5
Create Date: 2021-06-26 14:08:42.705501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'dcb1a0d764ee'
down_revision = '9a22d1c0c7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum = ENUM('IN_PROGRESS', 'FINISHED', 'OPPONENT_IN_PROGRESS', 'CLOSED', name='current_status', create_type=False)
    enum.create(op.get_bind(), checkfirst=False)

    op.add_column('quiz_games', sa.Column('current_status', enum, nullable=False))
    op.drop_column('quiz_games', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_games', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('quiz_games', 'current_status')
    # ### end Alembic commands ###
