"""Add is_active Column to Users Table

Revision ID: cd2bd35b2eea
Revises: 2d0a6ca8dfb7
Create Date: 2021-05-29 16:07:10.680783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2bd35b2eea'
down_revision = '2d0a6ca8dfb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
