"""Add quiz_games Table

Revision ID: 3b809ceaf543
Revises: 93696f4302ef
Create Date: 2021-06-26 11:44:36.541988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b809ceaf543'
down_revision = '93696f4302ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('current_assignee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_assignee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_games')
    # ### end Alembic commands ###
