"""Remove redundant Reference between quiz_game_question_answers and quiz_game_questions table

Revision ID: 643ba66d85b3
Revises: ff2d3520a35e
Create Date: 2021-06-28 22:17:12.071723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643ba66d85b3'
down_revision = 'ff2d3520a35e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quiz_game_question_answers_quizgame_question_id_fkey', 'quiz_game_question_answers', type_='foreignkey')
    op.drop_column('quiz_game_question_answers', 'quizgame_question_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_game_question_answers', sa.Column('quizgame_question_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('quiz_game_question_answers_quizgame_question_id_fkey', 'quiz_game_question_answers', 'quiz_game_questions', ['quizgame_question_id'], ['id'])
    # ### end Alembic commands ###
