"""Add new UserRoles Table

Revision ID: 59b8b5e7d35f
Revises: cd2bd35b2eea
Create Date: 2021-05-29 16:11:15.939756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b8b5e7d35f'
down_revision = 'cd2bd35b2eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userroles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userroles')
    # ### end Alembic commands ###
