"""Add Position Columns to quiz_game_questions and quiz_game_question_answers tables

Revision ID: ff2d3520a35e
Revises: 5b5a6fcee512
Create Date: 2021-06-28 22:01:46.166445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2d3520a35e'
down_revision = '5b5a6fcee512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_game_question_answers', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('quiz_game_questions', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_game_questions', 'position')
    op.drop_column('quiz_game_question_answers', 'position')
    # ### end Alembic commands ###
