"""Add quiz_game_setups Table

Revision ID: 822caa87a652
Revises: 3b809ceaf543
Create Date: 2021-06-26 11:48:17.948434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822caa87a652'
down_revision = '3b809ceaf543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_game_setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizquestion_text', sa.String(), nullable=False),
    sa.Column('quizquestion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quizquestion_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_game_setups')
    # ### end Alembic commands ###
