"""Add is_finalized Flag to quiz_game_results Table

Revision ID: 3e1ed6512132
Revises: 42565c1eb450
Create Date: 2021-08-01 09:40:18.239608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1ed6512132'
down_revision = '42565c1eb450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_game_results', sa.Column('is_finalized', sa.Boolean(), nullable=True, server_default='f'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_game_results', 'is_finalized')
    # ### end Alembic commands ###
