"""Add Relation to Subjects Table to QuizGames Table

Revision ID: 5b5a6fcee512
Revises: e5aa78243713
Create Date: 2021-06-27 21:12:44.237329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5a6fcee512'
down_revision = 'e5aa78243713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_games', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quiz_games', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_games', type_='foreignkey')
    op.drop_column('quiz_games', 'subject_id')
    # ### end Alembic commands ###
