"""Seed User Roles

Revision ID: 179266ed1559
Revises: b58314643d96
Create Date: 2021-05-29 16:21:19.686032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179266ed1559'
down_revision = 'b58314643d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute('INSERT INTO userroles(id, name) VALUES (1, \'student\');')
    op.execute('INSERT INTO userroles(id, name) VALUES (2, \'tutor\');')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute('DELETE FROM userroles WHERE id = 1;')
    op.execute('DELETE FROM userroles WHERE id = 2;')
