"""Remove Tutor Relation from QuizQuestions Table

Revision ID: 8621606a3a78
Revises: 643ba66d85b3
Create Date: 2021-06-29 20:57:53.413726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8621606a3a78'
down_revision = '643ba66d85b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quiz_questions_tutor_id_fkey', 'quiz_questions', type_='foreignkey')
    op.drop_column('quiz_questions', 'tutor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('tutor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('quiz_questions_tutor_id_fkey', 'quiz_questions', 'users', ['tutor_id'], ['id'])
    # ### end Alembic commands ###
