"""Add Subject Relation to QuizSuggestions Table

Revision ID: fe955ee50f86
Revises: 74f2412ed0bc
Create Date: 2021-06-05 11:34:13.101589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe955ee50f86'
down_revision = '74f2412ed0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_suggestions', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quiz_suggestions', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_suggestions', type_='foreignkey')
    op.drop_column('quiz_suggestions', 'subject_id')
    # ### end Alembic commands ###
