"""Add is_highscore_enabled Column to Users Table

Revision ID: a03454266773
Revises: d8d25eaedd3f
Create Date: 2021-07-23 22:49:01.934014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03454266773'
down_revision = 'd8d25eaedd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_highscore_enabled', sa.Boolean(), nullable=True, server_default='f'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_highscore_enabled')
    # ### end Alembic commands ###
