"""Add highscore_ranks Relation to users Table

Revision ID: 42565c1eb450
Revises: c36ed70c44b6
Create Date: 2021-07-29 22:11:50.983958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42565c1eb450'
down_revision = 'c36ed70c44b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('highscore_ranks_user_id_key', 'highscore_ranks', type_='unique')
    op.create_foreign_key(None, 'highscore_ranks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'highscore_ranks', type_='foreignkey')
    op.create_unique_constraint('highscore_ranks_user_id_key', 'highscore_ranks', ['user_id'])
    # ### end Alembic commands ###
