"""Add last_update DateTime to highscore_ranks Table

Revision ID: c36ed70c44b6
Revises: d0af6cad595b
Create Date: 2021-07-26 20:40:33.374226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36ed70c44b6'
down_revision = 'd0af6cad595b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highscore_ranks', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('highscore_ranks', 'last_update')
    # ### end Alembic commands ###
