"""Add Users Relation to QuizSuggestions Table

Revision ID: 6b675f132a29
Revises: fe955ee50f86
Create Date: 2021-06-05 11:36:15.599952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b675f132a29'
down_revision = 'fe955ee50f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_suggestions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quiz_suggestions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_suggestions', type_='foreignkey')
    op.drop_column('quiz_suggestions', 'user_id')
    # ### end Alembic commands ###
