"""Add highscore_alias Column to Users Table

Revision ID: 2b45c0cf66d3
Revises: a03454266773
Create Date: 2021-07-24 08:24:46.089929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b45c0cf66d3'
down_revision = 'a03454266773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('highscore_alias', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'users', ['highscore_alias'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'highscore_alias')
    # ### end Alembic commands ###
