"""Add QuizGameScores Tables

Revision ID: 457b7a8dd476
Revises: 8621606a3a78
Create Date: 2021-07-04 02:15:52.034813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457b7a8dd476'
down_revision = '8621606a3a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_game_question_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('quizgame_id', sa.Integer(), nullable=False),
    sa.Column('quizgamequestion_id', sa.Integer(), nullable=False),
    sa.Column('correct_quizgamequestionanswer_id', sa.Integer(), nullable=False),
    sa.Column('selected_quizgamequestionanswer_id', sa.Integer(), nullable=False),
    sa.Column('is_solved_correctly', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['correct_quizgamequestionanswer_id'], ['quiz_game_question_answers.id'], ),
    sa.ForeignKeyConstraint(['quizgame_id'], ['quiz_games.id'], ),
    sa.ForeignKeyConstraint(['quizgamequestion_id'], ['quiz_game_questions.id'], ),
    sa.ForeignKeyConstraint(['selected_quizgamequestionanswer_id'], ['quiz_game_question_answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_game_quiz_game_question_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizgame_id', sa.Integer(), nullable=True),
    sa.Column('quizgamequestionscore_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quizgame_id'], ['quiz_games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quizgamequestionscore_id'], ['quiz_game_question_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_game_quiz_game_question_scores')
    op.drop_table('quiz_game_question_scores')
    # ### end Alembic commands ###
