"""Add Relation between quiz_games and quiz_game_setups

Revision ID: 3ba75ef4c52b
Revises: 822caa87a652
Create Date: 2021-06-26 11:50:02.288035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba75ef4c52b'
down_revision = '822caa87a652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_games', sa.Column('quizgame_setup_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quiz_games', 'quiz_game_setups', ['quizgame_setup_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_games', type_='foreignkey')
    op.drop_column('quiz_games', 'quizgame_setup_id')
    # ### end Alembic commands ###
