"""Add quiz_game_setup_answers Table

Revision ID: c7d2a2663c19
Revises: 3ba75ef4c52b
Create Date: 2021-06-26 11:59:34.157974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d2a2663c19'
down_revision = '3ba75ef4c52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_game_setup_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizanswer_text', sa.String(), nullable=False),
    sa.Column('quizanswer_is_correct', sa.Boolean(), nullable=True),
    sa.Column('quizanswer_id', sa.Integer(), nullable=False),
    sa.Column('quizgamesetup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quizanswer_id'], ['quiz_answers.id'], ),
    sa.ForeignKeyConstraint(['quizgamesetup_id'], ['quiz_game_setups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_game_setup_answers')
    # ### end Alembic commands ###
