"""Add new highscore_ranks Table

Revision ID: 1a2932a77db7
Revises: 2b45c0cf66d3
Create Date: 2021-07-25 15:58:39.348931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2932a77db7'
down_revision = '2b45c0cf66d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highscore_ranks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('user_profilepicture', sa.String(), nullable=False),
    sa.Column('user_alias', sa.String(length=255), nullable=False),
    sa.Column('amount_of_games_won', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rank'),
    sa.UniqueConstraint('user_alias')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highscore_ranks')
    # ### end Alembic commands ###
